# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PYQT_asking_PageWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_asking_PageWindow(object):
    def setupUi(self, asking_PageWindow):
        asking_PageWindow.setObjectName("asking_PageWindow")
        asking_PageWindow.resize(400, 300)
        asking_PageWindow.setMouseTracking(False)
        self.winning_StatusLabel = QtWidgets.QLabel(asking_PageWindow)
        self.winning_StatusLabel.setGeometry(QtCore.QRect(50, 90, 321, 16))
        self.winning_StatusLabel.setObjectName("winning_StatusLabel")
        self.yesButton = QtWidgets.QPushButton(asking_PageWindow)
        self.yesButton.setGeometry(QtCore.QRect(230, 190, 151, 32))
        self.yesButton.setObjectName("yesButton")
        self.mainButton = QtWidgets.QPushButton(asking_PageWindow)
        self.mainButton.setGeometry(QtCore.QRect(230, 220, 151, 32))
        self.mainButton.setObjectName("mainButton")
        self.another_RoundLabel = QtWidgets.QLabel(asking_PageWindow)
        self.another_RoundLabel.setGeometry(QtCore.QRect(140, 150, 101, 16))
        self.another_RoundLabel.setObjectName("another_RoundLabel")

        self.retranslateUi(asking_PageWindow)
        self.yesButton.clicked.connect(asking_PageWindow.anotherRound)
        self.mainButton.clicked.connect(asking_PageWindow.transferMain)
        QtCore.QMetaObject.connectSlotsByName(asking_PageWindow)

    def retranslateUi(self, asking_PageWindow):
        _translate = QtCore.QCoreApplication.translate
        asking_PageWindow.setWindowTitle(_translate("asking_PageWindow", "PSR_ol"))
        self.winning_StatusLabel.setText(_translate("asking_PageWindow", "Error!"))
        self.yesButton.setText(_translate("asking_PageWindow", "yes"))
        self.mainButton.setText(_translate("asking_PageWindow", "no, send me to main"))
        self.another_RoundLabel.setText(_translate("asking_PageWindow", "Another Round? "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    asking_PageWindow = QtWidgets.QDialog()
    ui = Ui_asking_PageWindow()
    ui.setupUi(asking_PageWindow)
    asking_PageWindow.show()
    sys.exit(app.exec_())
