# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PYQT_fightWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_windowFight(object):
    def setupUi(self, windowFight):
        windowFight.setObjectName("windowFight")
        windowFight.resize(406, 419)
        self.first_SecondLabel = QtWidgets.QLabel(windowFight)
        self.first_SecondLabel.setGeometry(QtCore.QRect(20, 20, 231, 21))
        self.first_SecondLabel.setObjectName("first_SecondLabel")
        self.line_1 = QtWidgets.QFrame(windowFight)
        self.line_1.setGeometry(QtCore.QRect(190, 50, 16, 191))
        self.line_1.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setObjectName("line_1")
        self.player1_pictureLabel = QtWidgets.QLabel(windowFight)
        self.player1_pictureLabel.setGeometry(QtCore.QRect(30, 80, 131, 114))
        self.player1_pictureLabel.setText("")
        self.player1_pictureLabel.setPixmap(QtGui.QPixmap("images/Player.png"))
        self.player1_pictureLabel.setObjectName("player1_pictureLabel")
        self.line_2 = QtWidgets.QFrame(windowFight)
        self.line_2.setGeometry(QtCore.QRect(20, 260, 371, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.player2_statusLabel = QtWidgets.QLabel(windowFight)
        self.player2_statusLabel.setGeometry(QtCore.QRect(230, 90, 131, 101))
        self.player2_statusLabel.setObjectName("player2_statusLabel")
        self.layoutWidget = QtWidgets.QWidget(windowFight)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 281, 343, 32))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.paperButton = QtWidgets.QPushButton(self.layoutWidget)
        self.paperButton.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.paperButton.setStyleSheet("")
        self.paperButton.setObjectName("paperButton")
        self.horizontalLayout.addWidget(self.paperButton)
        self.scissorButton = QtWidgets.QPushButton(self.layoutWidget)
        self.scissorButton.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.scissorButton.setObjectName("scissorButton")
        self.horizontalLayout.addWidget(self.scissorButton)
        self.rockButton = QtWidgets.QPushButton(self.layoutWidget)
        self.rockButton.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.rockButton.setObjectName("rockButton")
        self.horizontalLayout.addWidget(self.rockButton)
        self.layoutWidget1 = QtWidgets.QWidget(windowFight)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 330, 381, 70))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.paper_ImageLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.paper_ImageLabel.setText("")
        self.paper_ImageLabel.setPixmap(QtGui.QPixmap("images/Paper.png"))
        self.paper_ImageLabel.setObjectName("paper_ImageLabel")
        self.horizontalLayout_2.addWidget(self.paper_ImageLabel)
        self.scissor_ImageLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.scissor_ImageLabel.setText("")
        self.scissor_ImageLabel.setPixmap(QtGui.QPixmap("images/Scissor.png"))
        self.scissor_ImageLabel.setObjectName("scissor_ImageLabel")
        self.horizontalLayout_2.addWidget(self.scissor_ImageLabel)
        self.rock_ImageLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.rock_ImageLabel.setText("")
        self.rock_ImageLabel.setPixmap(QtGui.QPixmap("images/Rock.png"))
        self.rock_ImageLabel.setObjectName("rock_ImageLabel")
        self.horizontalLayout_2.addWidget(self.rock_ImageLabel)
        self.checkButton = QtWidgets.QPushButton(windowFight)
        self.checkButton.setGeometry(QtCore.QRect(280, 20, 113, 32))
        self.checkButton.setObjectName("checkButton")
        self.player1_nameLabel = QtWidgets.QLabel(windowFight)
        self.player1_nameLabel.setGeometry(QtCore.QRect(30, 70, 121, 16))
        self.player1_nameLabel.setObjectName("player1_nameLabel")

        self.retranslateUi(windowFight)
        self.paperButton.clicked.connect(windowFight.paperClicked)
        self.scissorButton.clicked.connect(windowFight.scissorClicked)
        self.rockButton.clicked.connect(windowFight.rockClicked)
        self.checkButton.clicked.connect(windowFight.startFight)
        QtCore.QMetaObject.connectSlotsByName(windowFight)

    def retranslateUi(self, windowFight):
        _translate = QtCore.QCoreApplication.translate
        windowFight.setWindowTitle(_translate("windowFight", "PSR_ol"))
        self.first_SecondLabel.setText(_translate("windowFight", "Error!"))
        self.player2_statusLabel.setText(_translate("windowFight", "Error! "))
        self.paperButton.setText(_translate("windowFight", "Papper"))
        self.scissorButton.setText(_translate("windowFight", "Scissor"))
        self.rockButton.setText(_translate("windowFight", "Rock"))
        self.checkButton.setText(_translate("windowFight", "Start fight!"))
        self.player1_nameLabel.setText(_translate("windowFight", "Error!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    windowFight = QtWidgets.QWidget()
    ui = Ui_windowFight()
    ui.setupUi(windowFight)
    windowFight.show()
    sys.exit(app.exec_())
